package:
  format-version: "1.0.0"
  name: "smartenergy"
  version: "v1.1.0"
  type: "api"
  status: "production"
  required: true

  dependencies:
    - name: "dev_packs"
      type: "package"
      version: "v3.15.0"
    - name: "core"
      type: "package"
      version: "v3.12.0-E1"
    - name: "csp"
      type: "package"
      version: "v3.15.0"
    - name: "bsp"
      type: "package"
      version: "v3.15.0"
    - name: "harmony_gfx"
      type: "package"
      version: "v3.12.2"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.3.1"
