package:
  format-version: "1.0.0"
  name: "smartenergy"
  version: "v1.1.0"
  type: "api"
  status: "production"
  required: true

  dependencies:
    - name: "dev_packs"
      type: "package"
      version: "v3.13.2"
    - name: "core"
      type: "package"
      version: "v3.11.2"
    - name: "csp"
      type: "package"
      version: "v3.14.1"
    - name: "bsp"
      type: "package"
      version: "v3.14.1"
