package:
  format-version: "1.0.0"
  name: "smartenergy"
  version: "v1.2.1"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.19.1"
    - name: "core"
      type: "package"
      version: "v3.13.5"
    - name: "gfx"
      type: "package"
      version: "v3.13.0"
