package:
  format-version: "1.0.0"
  name: "smartenergy"
  version: "v1.2.0"
  type: "api"
  status: "production"
  required: true

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.16.1"
    - name: "csp"
      type: "package"
      version: "v3.17.0"
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "dev_packs"
      type: "package"
      version: "v3.17.0"
    - name: "gfx"
      type: "package"
      version: "v3.13.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
