package:
  format-version: "1.0.0"
  name: "smartenergy"
  version: "v1.3.0"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0"
    - name: "core"
      type: "package"
      version: "v3.14.0"
    - name: "gfx"
      type: "package"
      version: "v3.15.3"
