package:
  format-version: "1.0.0"
  name: "smartenergy"
  version: "v1.5.1"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.25.0"
    - name: "core"
      type: "package"
      version: "v3.16.0"
    - name: "gfx"
      type: "package"
      version: "v3.16.3"