/*******************************************************************************
  PLC Coupling Service Library Interface Header File

  Company
    Microchip Technology Inc.

  File Name
    srv_pcoup.h

  Summary
    PLC PHY Coupling service library interface.

  Description
    The Microchip G3-PLC and PRIME implementations include default PHY layer 
    configuration values optimized for the Evaluation Kits. With the help of 
    the PHY Calibration Tool it is possible to obtain the optimal configuration 
    values for the customer´s hardware implementation. Please refer to the 
    PL360 Host Controller document for more details about the available 
    configuration values and their purpose. 

  Remarks:
    This provides the required information to be included on PLC PHY projects 
    for PL360/PL460 in order to apply the custom calibration.
*******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
* Copyright (C) 2021 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
*******************************************************************************/
// DOM-IGNORE-END

#ifndef SRV_PCOUP_H    // Guards against multiple inclusion
#define SRV_PCOUP_H


// *****************************************************************************
// *****************************************************************************
// Section: Included Files
// *****************************************************************************
// *****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "system/system.h"
#include "driver/plc/phy/drv_plc_phy.h"

// DOM-IGNORE-BEGIN
#ifdef __cplusplus  // Provide C++ Compatibility

    extern "C" {

#endif
// DOM-IGNORE-END

/* PLC Phy Default Channel */
#define SRV_PCOUP_DEFAULT_CHANNEL                ${drvPlcPhy.DRV_PLC_PRIME_DEF_CHN?string}

/* Equalization number of coefficients (number of carriers) */
#define SRV_PCOUP_EQU_NUM_COEF_CHN               97
<#if (SRV_PCOUP_PRIME_CHANNELS_SELECTED >= 256)>
#define SRV_PCOUP_EQU_NUM_COEF_2_CHN             (SRV_PCOUP_EQU_NUM_COEF_CHN << 1)
</#if>

/* Specific gain for each carrier to equalize transmission and compensate HW filter frequency response */
<#if (SRV_PCOUP_PRIME_CHN1 == true)>
#define SRV_PCOUP_PRED_CHN1_HIGH_TBL             {0x756E, 0x7396, 0x730A, 0x72EB, 0x72B2, 0x7433, 0x755E, 0x75D7, 0x769E, 0x76A4, 0x77C3, 0x7851, 0x7864, 0x78A0, \
					                             0x78BA, 0x7918, 0x79B6, 0x79E9, 0x7ACC, 0x7B06, 0x7B30, 0x7B27, 0x7C1E, 0x7B96, 0x7A76, 0x7B12, 0x7AFD, 0x7C40, \
					                             0x7C5E, 0x7B48, 0x7B8A, 0x7C64, 0x7C42, 0x7BCD, 0x7AFD, 0x7A5F, 0x7A03, 0x7A9D, 0x7A1A, 0x7A4A, 0x79FC, 0x7984, \
					                             0x7A0D, 0x79CC, 0x792E, 0x780D, 0x7676, 0x75E4, 0x747A, 0x7251, 0x707E, 0x6E96, 0x6E30, 0x6D44, 0x6DBD, 0x6C9A, \
					                             0x6C3C, 0x6CF8, 0x6CA4, 0x6CDF, 0x6C59, 0x6B2C, 0x6CB9, 0x6C1F, 0x6B6D, 0x6BF5, 0x6AF0, 0x6A55, 0x6955, 0x674F, \
					                             0x6841, 0x685D, 0x670F, 0x6904, 0x6967, 0x6B01, 0x6C31, 0x6C2A, 0x6D82, 0x6F58, 0x6E62, 0x6F18, 0x6EE7, 0x7069, \
					                             0x717B, 0x7120, 0x7170, 0x72FB, 0x7491, 0x75B3, 0x75A2, 0x7664, 0x784A, 0x7A52, 0x7B51, 0x7D5A, 0x7FFF}

#define SRV_PCOUP_PRED_CHN1_VLOW_TBL             {0x7FFF, 0x7F2B, 0x7E38, 0x7CD3, 0x7B38, 0x7972, 0x77D6, 0x7654, 0x74AE, 0x7288, 0x70C0, 0x6E9A, 0x6D24, 0x6B80, \
					                             0x6A2F, 0x6852, 0x674E, 0x65DA, 0x652E, 0x637E, 0x6292, 0x6142, 0x60CC, 0x5FF8, 0x5F6D, 0x5EC2, 0x5E6F, 0x5E55, \
					                             0x5E43, 0x5E02, 0x5E5B, 0x5EB3, 0x5F4A, 0x5FD7, 0x604C, 0x60FC, 0x61F3, 0x6297, 0x63A9, 0x643D, 0x654A, 0x6634, \
					                             0x675C, 0x6824, 0x6910, 0x69A4, 0x6A73, 0x6B6F, 0x6C15, 0x6CCD, 0x6D64, 0x6E4B, 0x6ED3, 0x6F44, 0x6F85, 0x70A1, \
					                             0x70AF, 0x71B2, 0x7149, 0x71F3, 0x7203, 0x7279, 0x71FB, 0x72B4, 0x7281, 0x72A4, 0x7262, 0x72BD, 0x7295, 0x72CC, \
					                             0x729E, 0x7288, 0x7244, 0x7279, 0x726C, 0x7230, 0x71B9, 0x70D8, 0x7045, 0x7052, 0x6F8D, 0x6F3D, 0x6EB0, 0x6E6A, \
					                             0x6E76, 0x6E1C, 0x6D7A, 0x6D84, 0x6D50, 0x6D45, 0x6CF2, 0x6CA9, 0x6C92, 0x6CBA, 0x6C69, 0x6C27, 0x6C02}

</#if>
<#if ((SRV_PCOUP_PRIME_CHN2 == true) || (SRV_PCOUP_PRIME_CHN3 == true) || (SRV_PCOUP_PRIME_CHN4 == true) || (SRV_PCOUP_PRIME_CHN5 == true) || (SRV_PCOUP_PRIME_CHN6 == true) || (SRV_PCOUP_PRIME_CHN7 == true) || (SRV_PCOUP_PRIME_CHN8 == true))>
#define SRV_PCOUP_PRED_NOT_USED                  {0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
					                             0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
					                             0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
					                             0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
					                             0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
					                             0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
					                             0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF}

</#if>
<#if (SRV_PCOUP_PRIME_CHANNELS_SELECTED >= 256)>
#define SRV_PCOUP_PRED_2CHN_NOT_USED             {0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, \
                                                 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF}

</#if>
/* DACC configuration */
<#if (SRV_PCOUP_PRIME_CHN1 == true)>
#define SRV_PCOUP_DACC_CENA_TBL                  {0x${SRV_PCOUP_DACC_CENA_0?string}, 0x${SRV_PCOUP_DACC_CENA_1?string}, 0x${SRV_PCOUP_DACC_CENA_2?string}, 0x${SRV_PCOUP_DACC_CENA_3?string}, 0x${SRV_PCOUP_DACC_CENA_4?string}, 0x${SRV_PCOUP_DACC_CENA_5?string}, \
                                                 0x${SRV_PCOUP_DACC_CENA_6?string}, 0x${SRV_PCOUP_DACC_CENA_7?string}, 0x${SRV_PCOUP_DACC_CENA_8?string}, 0x${SRV_PCOUP_DACC_CENA_9?string}, 0x${SRV_PCOUP_DACC_CENA_10?string}, 0x${SRV_PCOUP_DACC_CENA_11?string}, \
                                                 0x${SRV_PCOUP_DACC_CENA_12?string}, 0x${SRV_PCOUP_DACC_CENA_13?string}, 0x${SRV_PCOUP_DACC_CENA_14?string}, 0x${SRV_PCOUP_DACC_CENA_15?string}, 0x${SRV_PCOUP_DACC_CENA_16?string}}

</#if>
<#if ((SRV_PCOUP_PRIME_CHN2 == true) || (SRV_PCOUP_PRIME_CHN3 == true) || (SRV_PCOUP_PRIME_CHN4 == true) || (SRV_PCOUP_PRIME_CHN5 == true) || (SRV_PCOUP_PRIME_CHN6 == true) || (SRV_PCOUP_PRIME_CHN7 == true) || (SRV_PCOUP_PRIME_CHN8 == true))>
#define SRV_PCOUP_DACC_FCC_TBL                   {0x${SRV_PCOUP_DACC_FCC_0?string}, 0x${SRV_PCOUP_DACC_FCC_1?string}, 0x${SRV_PCOUP_DACC_FCC_2?string}, 0x${SRV_PCOUP_DACC_FCC_3?string}, 0x${SRV_PCOUP_DACC_FCC_4?string}, 0x${SRV_PCOUP_DACC_FCC_5?string}, \
                                                 0x${SRV_PCOUP_DACC_FCC_6?string}, 0x${SRV_PCOUP_DACC_FCC_7?string}, 0x${SRV_PCOUP_DACC_FCC_8?string}, 0x${SRV_PCOUP_DACC_FCC_9?string}, 0x${SRV_PCOUP_DACC_FCC_10?string}, 0x${SRV_PCOUP_DACC_FCC_11?string}, \
                                                 0x${SRV_PCOUP_DACC_FCC_12?string}, 0x${SRV_PCOUP_DACC_FCC_13?string}, 0x${SRV_PCOUP_DACC_FCC_14?string}, 0x${SRV_PCOUP_DACC_FCC_15?string}, 0x${SRV_PCOUP_DACC_FCC_16?string}}

</#if>
<#if (SRV_PCOUP_PRIME_CHANNELS_SELECTED >= 256)>
#define SRV_PCOUP_DACC_2CHN_TBL                  {0x${SRV_PCOUP_DACC_2CHN_0?string}, 0x${SRV_PCOUP_DACC_2CHN_1?string}, 0x${SRV_PCOUP_DACC_2CHN_2?string}, 0x${SRV_PCOUP_DACC_2CHN_3?string}, 0x${SRV_PCOUP_DACC_2CHN_4?string}, 0x${SRV_PCOUP_DACC_2CHN_5?string}, \
                                                 0x${SRV_PCOUP_DACC_2CHN_6?string}, 0x${SRV_PCOUP_DACC_2CHN_7?string}, 0x${SRV_PCOUP_DACC_2CHN_8?string}, 0x${SRV_PCOUP_DACC_2CHN_9?string}, 0x${SRV_PCOUP_DACC_2CHN_10?string}, 0x${SRV_PCOUP_DACC_2CHN_11?string}, \
                                                 0x${SRV_PCOUP_DACC_2CHN_12?string}, 0x${SRV_PCOUP_DACC_2CHN_13?string}, 0x${SRV_PCOUP_DACC_2CHN_14?string}, 0x${SRV_PCOUP_DACC_2CHN_15?string}, 0x${SRV_PCOUP_DACC_2CHN_16?string}}

</#if>

/* Channel Configurations */
<#if (SRV_PCOUP_PRIME_CHN1 == true)>
#define SRV_PCOUP_CHN1_RMS_HIGH_TBL              {${SRV_PCOUP_PRIME_CHN1_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN1_RMS_VLOW_TBL              {${SRV_PCOUP_PRIME_CHN1_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN1_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN1_THRS_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN1_THRS_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_CHN1_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN1_GAIN_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN1_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN1_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN1_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN1_GAIN_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN1_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN1_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN1_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN1_LINE_DRV_CONF             ${SRV_PCOUP_PRIME_CHN1_LINE_DRIVER?string}
#define SRV_PCOUP_CHN1_MAX_NUM_TX_LEVELS         ${SRV_PCOUP_PRIME_CHN1_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_CHN2 == true)>
#define SRV_PCOUP_CHN2_RMS_HIGH_TBL              {${SRV_PCOUP_PRIME_CHN2_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN2_RMS_VLOW_TBL              {${SRV_PCOUP_PRIME_CHN2_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN2_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN2_THRS_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN2_THRS_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_CHN2_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN2_GAIN_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN2_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN2_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN2_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN2_GAIN_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN2_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN2_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN2_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN2_LINE_DRV_CONF             ${SRV_PCOUP_PRIME_CHN2_LINE_DRIVER?string}
#define SRV_PCOUP_CHN2_MAX_NUM_TX_LEVELS         ${SRV_PCOUP_PRIME_CHN2_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_CHN3 == true)>
#define SRV_PCOUP_CHN3_RMS_HIGH_TBL              {${SRV_PCOUP_PRIME_CHN3_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN3_RMS_VLOW_TBL              {${SRV_PCOUP_PRIME_CHN3_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN3_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN3_THRS_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN3_THRS_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_CHN3_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN3_GAIN_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN3_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN3_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN3_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN3_GAIN_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN3_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN3_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN3_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN3_LINE_DRV_CONF             ${SRV_PCOUP_PRIME_CHN3_LINE_DRIVER?string}
#define SRV_PCOUP_CHN3_MAX_NUM_TX_LEVELS         ${SRV_PCOUP_PRIME_CHN3_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_CHN4 == true)>
#define SRV_PCOUP_CHN4_RMS_HIGH_TBL              {${SRV_PCOUP_PRIME_CHN4_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN4_RMS_VLOW_TBL              {${SRV_PCOUP_PRIME_CHN4_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN4_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN4_THRS_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN4_THRS_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_CHN4_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN4_GAIN_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN4_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN4_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN4_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN4_GAIN_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN4_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN4_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN4_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN4_LINE_DRV_CONF             ${SRV_PCOUP_PRIME_CHN4_LINE_DRIVER?string}
#define SRV_PCOUP_CHN4_MAX_NUM_TX_LEVELS         ${SRV_PCOUP_PRIME_CHN4_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_CHN5 == true)>
#define SRV_PCOUP_CHN5_RMS_HIGH_TBL              {${SRV_PCOUP_PRIME_CHN5_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN5_RMS_VLOW_TBL              {${SRV_PCOUP_PRIME_CHN5_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN5_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN5_THRS_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN5_THRS_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_CHN5_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN5_GAIN_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN5_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN5_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN5_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN5_GAIN_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN5_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN5_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN5_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN5_LINE_DRV_CONF             ${SRV_PCOUP_PRIME_CHN5_LINE_DRIVER?string}
#define SRV_PCOUP_CHN5_MAX_NUM_TX_LEVELS         ${SRV_PCOUP_PRIME_CHN5_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_CHN6 == true)>
#define SRV_PCOUP_CHN6_RMS_HIGH_TBL              {${SRV_PCOUP_PRIME_CHN6_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN6_RMS_VLOW_TBL              {${SRV_PCOUP_PRIME_CHN6_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN6_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN6_THRS_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN6_THRS_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_CHN6_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN6_GAIN_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN6_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN6_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN6_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN6_GAIN_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN6_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN6_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN6_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN6_LINE_DRV_CONF             ${SRV_PCOUP_PRIME_CHN6_LINE_DRIVER?string}
#define SRV_PCOUP_CHN6_MAX_NUM_TX_LEVELS         ${SRV_PCOUP_PRIME_CHN6_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_CHN7 == true)>
#define SRV_PCOUP_CHN7_RMS_HIGH_TBL              {${SRV_PCOUP_PRIME_CHN7_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN7_RMS_VLOW_TBL              {${SRV_PCOUP_PRIME_CHN7_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN7_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN7_THRS_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN7_THRS_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_CHN7_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN7_GAIN_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN7_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN7_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN7_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN7_GAIN_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN7_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN7_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN7_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN7_LINE_DRV_CONF             ${SRV_PCOUP_PRIME_CHN7_LINE_DRIVER?string}
#define SRV_PCOUP_CHN7_MAX_NUM_TX_LEVELS         ${SRV_PCOUP_PRIME_CHN7_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_CHN8 == true)>
#define SRV_PCOUP_CHN8_RMS_HIGH_TBL              {${SRV_PCOUP_PRIME_CHN8_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN8_RMS_VLOW_TBL              {${SRV_PCOUP_PRIME_CHN8_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN8_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN8_THRS_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN8_THRS_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_CHN8_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN8_GAIN_HIGH_TBL             {${SRV_PCOUP_PRIME_CHN8_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_CHN8_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_CHN8_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN8_GAIN_VLOW_TBL             {${SRV_PCOUP_PRIME_CHN8_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_CHN8_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_CHN8_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN8_LINE_DRV_CONF             ${SRV_PCOUP_PRIME_CHN8_LINE_DRIVER?string}
#define SRV_PCOUP_CHN8_MAX_NUM_TX_LEVELS         ${SRV_PCOUP_PRIME_CHN8_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_2CHN12 == true)>
#define SRV_PCOUP_CHN12_RMS_HIGH_TBL             {${SRV_PCOUP_PRIME_2CHN12_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN12_RMS_VLOW_TBL             {${SRV_PCOUP_PRIME_2CHN12_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN12_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN12_THRS_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN12_THRS_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_2CHN12_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN12_GAIN_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN12_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN12_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN12_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN12_GAIN_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN12_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN12_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN12_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN12_LINE_DRV_CONF            ${SRV_PCOUP_PRIME_2CHN12_LINE_DRIVER?string}
#define SRV_PCOUP_CHN12_MAX_NUM_TX_LEVELS        ${SRV_PCOUP_PRIME_2CHN12_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_2CHN23 == true)>
#define SRV_PCOUP_CHN23_RMS_HIGH_TBL             {${SRV_PCOUP_PRIME_2CHN23_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN23_RMS_VLOW_TBL             {${SRV_PCOUP_PRIME_2CHN23_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN23_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN23_THRS_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN23_THRS_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_2CHN23_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN23_GAIN_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN23_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN23_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN23_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN23_GAIN_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN23_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN23_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN23_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN23_LINE_DRV_CONF            ${SRV_PCOUP_PRIME_2CHN23_LINE_DRIVER?string}
#define SRV_PCOUP_CHN23_MAX_NUM_TX_LEVELS        ${SRV_PCOUP_PRIME_2CHN23_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_2CHN34 == true)>
#define SRV_PCOUP_CHN34_RMS_HIGH_TBL             {${SRV_PCOUP_PRIME_2CHN34_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN34_RMS_VLOW_TBL             {${SRV_PCOUP_PRIME_2CHN34_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN34_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN34_THRS_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN34_THRS_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_2CHN34_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN34_GAIN_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN34_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN34_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN34_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN34_GAIN_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN34_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN34_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN34_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN34_LINE_DRV_CONF            ${SRV_PCOUP_PRIME_2CHN34_LINE_DRIVER?string}
#define SRV_PCOUP_CHN34_MAX_NUM_TX_LEVELS        ${SRV_PCOUP_PRIME_2CHN34_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_2CHN45 == true)>
#define SRV_PCOUP_CHN45_RMS_HIGH_TBL             {${SRV_PCOUP_PRIME_2CHN45_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN45_RMS_VLOW_TBL             {${SRV_PCOUP_PRIME_2CHN45_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN45_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN45_THRS_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN45_THRS_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_2CHN45_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN45_GAIN_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN45_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN45_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN45_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN45_GAIN_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN45_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN45_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN45_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN45_LINE_DRV_CONF            ${SRV_PCOUP_PRIME_2CHN45_LINE_DRIVER?string}
#define SRV_PCOUP_CHN45_MAX_NUM_TX_LEVELS        ${SRV_PCOUP_PRIME_2CHN45_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_2CHN56 == true)>
#define SRV_PCOUP_CHN56_RMS_HIGH_TBL             {${SRV_PCOUP_PRIME_2CHN56_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN56_RMS_VLOW_TBL             {${SRV_PCOUP_PRIME_2CHN56_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN56_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN56_THRS_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN56_THRS_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_2CHN56_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN56_GAIN_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN56_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN56_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN56_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN56_GAIN_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN56_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN56_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN56_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN56_LINE_DRV_CONF            ${SRV_PCOUP_PRIME_2CHN56_LINE_DRIVER?string}
#define SRV_PCOUP_CHN56_MAX_NUM_TX_LEVELS        ${SRV_PCOUP_PRIME_2CHN56_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_2CHN67 == true)>
#define SRV_PCOUP_CHN67_RMS_HIGH_TBL             {${SRV_PCOUP_PRIME_2CHN67_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN67_RMS_VLOW_TBL             {${SRV_PCOUP_PRIME_2CHN67_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN67_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN67_THRS_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN67_THRS_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_2CHN67_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN67_GAIN_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN67_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN67_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN67_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN67_GAIN_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN67_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN67_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN67_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN67_LINE_DRV_CONF            ${SRV_PCOUP_PRIME_2CHN67_LINE_DRIVER?string}
#define SRV_PCOUP_CHN67_MAX_NUM_TX_LEVELS        ${SRV_PCOUP_PRIME_2CHN67_NUM_TX_LVL?string}

</#if>
<#if (SRV_PCOUP_PRIME_2CHN78 == true)>
#define SRV_PCOUP_CHN78_RMS_HIGH_TBL             {${SRV_PCOUP_PRIME_2CHN78_RMS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_HIGH_7?string}}
#define SRV_PCOUP_CHN78_RMS_VLOW_TBL             {${SRV_PCOUP_PRIME_2CHN78_RMS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN78_RMS_VLOW_7?string}}
#define SRV_PCOUP_CHN78_THRS_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_2?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_3?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_4?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_5?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_6?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_7?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_8?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_9?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_10?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_11?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_12?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_13?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_14?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_HIGH_15?string}}
#define SRV_PCOUP_CHN78_THRS_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_2?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_3?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_4?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_5?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_6?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_7?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_8?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_9?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_10?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_11?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_12?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_13?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_14?string}, ${SRV_PCOUP_PRIME_2CHN78_THRS_VLOW_15?string}}
#define SRV_PCOUP_CHN78_GAIN_HIGH_TBL            {${SRV_PCOUP_PRIME_2CHN78_GAIN_HIGH_0?string}, ${SRV_PCOUP_PRIME_2CHN78_GAIN_HIGH_1?string}, ${SRV_PCOUP_PRIME_2CHN78_GAIN_HIGH_2?string}}
#define SRV_PCOUP_CHN78_GAIN_VLOW_TBL            {${SRV_PCOUP_PRIME_2CHN78_GAIN_VLOW_0?string}, ${SRV_PCOUP_PRIME_2CHN78_GAIN_VLOW_1?string}, ${SRV_PCOUP_PRIME_2CHN78_GAIN_VLOW_2?string}}
#define SRV_PCOUP_CHN78_LINE_DRV_CONF            ${SRV_PCOUP_PRIME_2CHN78_LINE_DRIVER?string}
#define SRV_PCOUP_CHN78_MAX_NUM_TX_LEVELS        ${SRV_PCOUP_PRIME_2CHN78_NUM_TX_LVL?string}

</#if>

// *****************************************************************************
// *****************************************************************************
// Section: Data Types
// *****************************************************************************
// *****************************************************************************
// *****************************************************************************
/* PLC Phy Coupling Channel definitions

 Summary:
    Defines transmission channels.

 Description:
    This will be used to indicate the channel to work with.

 Remarks:
    None.
*/

typedef enum
{
    CHN1 = 1,
    CHN2,
    CHN3,
    CHN4,
    CHN5,
    CHN6,
    CHN7,
    CHN8,
    CHN1_CHN2 = 9,
    CHN2_CHN3,
    CHN3_CHN4,
    CHN4_CHN5,
    CHN5_CHN6,
    CHN6_CHN7,
    CHN7_CHN8
} SRV_PLC_PCOUP_CHANNEL;     

// *****************************************************************************
/* PLC Phy Coupling Interface Data

  Summary:
    Defines the data required to initialize the PLC PHY Coupling Interface.

  Description:
    This data type defines the data required to initialize the PLC PHY Coupling
    Interface.

  Remarks:
    None.
*/

typedef struct
{  
    /* Target RMS high values for each Transmission */
    uint32_t rmsHigh[8];
    
    /* Target RMS very low values for each Transmission */
    uint32_t rmsVLow[8];
    
    /* Table of thresholds to automatically update Tx Mode from HIGH mode */
    uint32_t thrsHigh[16];
    
    /* Table of thresholds to automatically update Tx Mode from VLOW mode */
    uint32_t thrsVLow[16];

    /* Configuration values of DACC peripheral according to hardware configuration */
    const uint32_t * daccTable;
    
    /* Pointer to equalization Coefficients table in HIGH Tx mode. There is one coefficient for each carrier in the used band */
    const uint16_t * equHigh;
    
    /* Pointer to equalization Coefficients table in VLOW Tx mode. There is one coefficient for each carrier in the used band */
    const uint16_t * equVlow;
    
    /* Table of gain values for HIGH Tx Mode [HIGH_INI, HIGH_MIN, HIGH_MAX] */
    uint16_t gainHigh[3];
    
    /* Table of gain values for VLOW Tx Mode [VLOW_INI, VLOW_MIN, VLOW_MAX] */
    uint16_t gainVLow[3];
    
    /* Number of Tx attenuation levels (3 dB steps) for normal transmission behavior */
    uint8_t numTxLevels;
    
    /* Configuration of the embedded PLC Line Driver */
    uint8_t lineDrvConf;

} SRV_PLC_PCOUP_CHANNEL_DATA;

// *****************************************************************************
// *****************************************************************************
// Section: Service Interface Functions
// *****************************************************************************
// *****************************************************************************

/***************************************************************************
  Function:
    SRV_PLC_PCOUP_CHANNEL SRV_PCOUP_Get_Default_Channel(void)
    
  Summary:
    Get the transmission channel which has been configured by default.

  Description:
    This function is used to Get the default tranmission channel of the 
    PLC PHY Coupling.

  Precondition:
    None.

  Parameters:
    None.

  Returns:
    SRV_PLC_PCOUP_CHANNEL - Indicates the tranmission channel by default.

  Example:
    <code>
    SRV_PLC_PCOUP_CHANNEL plcDefaultChannel;
    SRV_PLC_PCOUP_CHANNEL_DATA *pCoupChannelData;

    plcDefaultChannel = SRV_PCOUP_Get_Default_Channel();
    pCoupChannelData = SRV_PCOUP_Get_Channel_Config(plcDefaultChannel);
    </code>

  Remarks:
    None.
  ***************************************************************************/

SRV_PLC_PCOUP_CHANNEL SRV_PCOUP_Get_Default_Channel( void );

/***************************************************************************
  Function:
    SRV_PLC_PCOUP_CHANNEL_DATA * SRV_PCOUP_Get_Channel_Config(SRV_PLC_PCOUP_CHANNEL channel)
    
  Summary:
    Get the proper parameters to configure the PLC PHY Coupling according to
    the customer values.

  Description:
    This function is used to Get the proper parameters to configure the 
    PLC PHY Coupling. This parameters should be sent to the PLC device through
    PIB interface.

  Precondition:
    None.

  Parameters:
    channel   - Channel from which the parameters are obtained

  Returns:
    NULL      - Indicates that the channel has not been selected in the configuration of the application and
                its configuration is not available.

    Pointer to PLC PHY Coupling parameters to be used.

  Example:
    <code>
    SRV_PLC_PCOUP_CHANNEL_DATA *pCoupChannelData;

    pCoupChannelData = SRV_PCOUP_Get_Channel_Config(SRV_PCOUP_DEFAULT_CHANNEL);
    </code>

  Remarks:
    None.
  ***************************************************************************/

SRV_PLC_PCOUP_CHANNEL_DATA * SRV_PCOUP_Get_Channel_Config(SRV_PLC_PCOUP_CHANNEL channel);

/***************************************************************************
  Function:
    bool SRV_PCOUP_Set_Channel_Config(DRV_HANDLE handle, SRV_PLC_PCOUP_CHANNEL channel);
    
  Summary:
    Set the PLC Tx Coupling PHY parameters for the desired transmission channel.

  Description:
    This function is used to set the PLC Tx Coupling PHY parameters for the 
    desired transmission channel, using the PLC Driver PIB interface.

  Precondition:
    DRV_PLC_PHY_Open must have been called to obtain a valid driver handle.

  Parameters:
    handle  - PLC driver handle used to set PIB parameters
    channel  - Transmission channel for which the parameters will be set

  Returns:
    true    - Successful configuration
    false   - Failed configuration

  Example:
    <code>
    // 'handle', returned from the DRV_PLC_PHY_Open
    bool result;

    result = SRV_PCOUP_Set_Channel_Config(handle, CHN5);
    </code>

  Remarks:
    None.
  ***************************************************************************/

bool SRV_PCOUP_Set_Channel_Config(DRV_HANDLE handle, SRV_PLC_PCOUP_CHANNEL channel);

// DOM-IGNORE-BEGIN
#ifdef __cplusplus  // Provide C++ Compatibility

    }

#endif
// DOM-IGNORE-END

#endif //SRV_PCOUP_H
